Fix unexpected NoMethodError (#42)
* Fix unexpected NoMethodError

When access to document root "/" is recorded, command is set to
nil. It causes the following error when calling command.arguments in
 #to_hash method because to_hash doesn't care command==nil case.

  NoMethodError: undefined method `arguments' for nil:NilClass

* Remove needless assignment